"""Initial migration

Revision ID: 03e6ef7bacfe
Revises:
Create Date: 2025-11-22 22:15:04.186339

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03e6ef7bacfe"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification_mappings",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("source_scheme", sa.Text(), nullable=False),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column("target_scheme", sa.Text(), nullable=False),
        sa.Column("target_code", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("mapping_source", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "source_scheme", "source_code", "target_scheme"),
    )
    op.create_index(
        op.f("ix_classification_mappings_org_id"),
        "classification_mappings",
        ["org_id"],
        unique=False,
    )
    op.create_table(
        "data_sync_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_failed", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('SUCCESS', 'FAILED', 'PARTIAL_SUCCESS', 'SKIPPED')",
            name="check_sync_status_valid",
        ),
        sa.CheckConstraint(
            "records_failed >= 0", name="check_records_failed_non_negative"
        ),
        sa.CheckConstraint(
            "records_inserted >= 0", name="check_records_inserted_non_negative"
        ),
        sa.CheckConstraint(
            "records_updated >= 0", name="check_records_updated_non_negative"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sync_failures", "data_sync_log", ["status", "run_timestamp"], unique=False
    )
    op.create_index(
        "idx_sync_run", "data_sync_log", ["run_timestamp", "source_name"], unique=False
    )
    op.create_index(
        "idx_sync_source_health",
        "data_sync_log",
        ["source_name", "status", "run_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_sync_log_run_timestamp"),
        "data_sync_log",
        ["run_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_sync_log_source_name"),
        "data_sync_log",
        ["source_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_sync_log_status"), "data_sync_log", ["status"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("doc_metadata", sa.JSON(), nullable=False),
        sa.Column("doc_type", sa.Text(), nullable=True),
        sa.Column("source_file", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_doc_type"), "documents", ["doc_type"], unique=False
    )
    op.create_table(
        "ingest_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=True),
        sa.Column("items_total", sa.Integer(), nullable=False),
        sa.Column("items_added", sa.Integer(), nullable=False),
        sa.Column("items_modified", sa.Integer(), nullable=False),
        sa.Column("items_unchanged", sa.Integer(), nullable=False),
        sa.Column("items_deleted", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.Integer(), nullable=False),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed', 'cancelled')",
            name="check_ingest_status_valid",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ingest_org_project_started",
        "ingest_logs",
        ["org_id", "project_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_logs_org_id"), "ingest_logs", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_logs_project_id"), "ingest_logs", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_logs_started_at"), "ingest_logs", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_logs_status"), "ingest_logs", ["status"], unique=False
    )
    op.create_table(
        "item_mapping",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("canonical_key", sa.Text(), nullable=False),
        sa.Column("price_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "start_ts",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("end_ts", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "end_ts IS NULL OR end_ts > start_ts", name="check_valid_period"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_id", "canonical_key", "start_ts", name="uq_mapping_start"
        ),
    )
    op.create_index(
        "idx_mapping_active",
        "item_mapping",
        ["org_id", "canonical_key"],
        unique=True,
        postgresql_where=sa.text("end_ts IS NULL"),
        sqlite_where=sa.text("end_ts IS NULL"),
    )
    op.create_index(
        "idx_mapping_temporal",
        "item_mapping",
        ["org_id", "canonical_key", "start_ts", "end_ts"],
        unique=False,
    )
    op.create_table(
        "item_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("ingest_timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("source_filename", sa.Text(), nullable=True),
        sa.Column("field_name", sa.Text(), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("change_type", sa.Text(), nullable=False),
        sa.Column(
            "detected_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "change_type IN ('added', 'modified', 'deleted', 'unchanged')",
            name="check_change_type_valid",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_revisions_item_field",
        "item_revisions",
        ["item_id", "field_name"],
        unique=False,
    )
    op.create_index(
        "idx_revisions_org_project_timestamp",
        "item_revisions",
        ["org_id", "project_id", "ingest_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_revisions_change_type"),
        "item_revisions",
        ["change_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_revisions_field_name"),
        "item_revisions",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_revisions_ingest_timestamp"),
        "item_revisions",
        ["ingest_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_revisions_item_id"), "item_revisions", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_item_revisions_org_id"), "item_revisions", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_item_revisions_project_id"),
        "item_revisions",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("classification_code", sa.Integer(), nullable=True),
        sa.Column("canonical_key", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("family", sa.Text(), nullable=False),
        sa.Column("type_name", sa.Text(), nullable=False),
        sa.Column("system_type", sa.Text(), nullable=True),
        sa.Column("omniclass_code", sa.Integer(), nullable=True),
        sa.Column("uniformat_code", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("width_mm", sa.Float(), nullable=True),
        sa.Column("height_mm", sa.Float(), nullable=True),
        sa.Column("dn_mm", sa.Float(), nullable=True),
        sa.Column("angle_deg", sa.Float(), nullable=True),
        sa.Column("material", sa.Text(), nullable=True),
        sa.Column("source_file", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_items_canonical", "items", ["canonical_key"], unique=False)
    op.create_index("idx_items_class", "items", ["classification_code"], unique=False)
    op.create_index(
        op.f("ix_items_canonical_key"), "items", ["canonical_key"], unique=False
    )
    op.create_index(
        op.f("ix_items_classification_code"),
        "items",
        ["classification_code"],
        unique=False,
    )
    op.create_index(op.f("ix_items_org_id"), "items", ["org_id"], unique=False)
    op.create_index(op.f("ix_items_project_id"), "items", ["project_id"], unique=False)
    op.create_table(
        "match_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("price_item_id", sa.Uuid(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('auto-accepted', 'manual-review', 'rejected')",
            name="check_decision_valid",
        ),
        sa.CheckConstraint(
            "source IN ('mapping_memory', 'fuzzy_match', 'review_ui')",
            name="check_source_valid",
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 100",
            name="check_confidence_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_results_decision"), "match_results", ["decision"], unique=False
    )
    op.create_index(
        op.f("ix_match_results_item_id"), "match_results", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_results_price_item_id"),
        "match_results",
        ["price_item_id"],
        unique=False,
    )
    op.create_table(
        "price_import_runs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("items_fetched", sa.Integer(), nullable=False),
        sa.Column("items_loaded", sa.Integer(), nullable=False),
        sa.Column("items_rejected", sa.Integer(), nullable=False),
        sa.Column("rejection_reasons", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_import_runs_org_id"),
        "price_import_runs",
        ["org_id"],
        unique=False,
    )
    op.create_table(
        "match_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("match_result_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("price_item_id", sa.Uuid(), nullable=False),
        sa.Column("flag_type", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('Critical-Veto', 'Advisory')", name="check_severity_valid"
        ),
        sa.ForeignKeyConstraint(
            ["match_result_id"], ["match_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_flags_item", "match_flags", ["item_id"], unique=False)
    op.create_index(
        "idx_flags_match_result", "match_flags", ["match_result_id"], unique=False
    )
    op.create_index("idx_flags_price", "match_flags", ["price_item_id"], unique=False)
    op.create_index("idx_flags_severity", "match_flags", ["severity"], unique=False)
    op.create_index(
        op.f("ix_match_flags_item_id"), "match_flags", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_flags_match_result_id"),
        "match_flags",
        ["match_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_match_flags_price_item_id"),
        "match_flags",
        ["price_item_id"],
        unique=False,
    )
    op.create_table(
        "price_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("item_code", sa.Text(), nullable=False),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("classification_code", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Text(), nullable=True),
        sa.Column("vendor_code", sa.Text(), nullable=True),
        sa.Column("sku", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("width_mm", sa.Float(), nullable=True),
        sa.Column("height_mm", sa.Float(), nullable=True),
        sa.Column("dn_mm", sa.Float(), nullable=True),
        sa.Column("angle_deg", sa.Float(), nullable=True),
        sa.Column("material", sa.Text(), nullable=True),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("source_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "original_effective_date", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "valid_from",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "last_updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("vendor_note", sa.Text(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("import_run_id", sa.Text(), nullable=True),
        sa.CheckConstraint("unit_price >= 0", name="check_unit_price_non_negative"),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="check_valid_period"
        ),
        sa.ForeignKeyConstraint(
            ["import_run_id"], ["price_import_runs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_price_active_unique",
        "price_items",
        ["org_id", "item_code", "region"],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
        sqlite_where=sa.text("is_current = 1"),
    )
    op.create_index(
        "idx_price_class", "price_items", ["classification_code"], unique=False
    )
    op.create_index(
        "idx_price_current",
        "price_items",
        ["org_id", "item_code", "region", "is_current"],
        unique=False,
    )
    op.create_index(
        "idx_price_source", "price_items", ["source_name", "last_updated"], unique=False
    )
    op.create_index(
        "idx_price_temporal",
        "price_items",
        ["org_id", "item_code", "region", "valid_from", "valid_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_items_classification_code"),
        "price_items",
        ["classification_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_items_import_run_id"),
        "price_items",
        ["import_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_items_is_current"), "price_items", ["is_current"], unique=False
    )
    op.create_index(
        op.f("ix_price_items_item_code"), "price_items", ["item_code"], unique=False
    )
    op.create_index(
        op.f("ix_price_items_org_id"), "price_items", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_price_items_region"), "price_items", ["region"], unique=False
    )
    op.create_index(op.f("ix_price_items_sku"), "price_items", ["sku"], unique=False)
    op.create_index(
        op.f("ix_price_items_source_name"), "price_items", ["source_name"], unique=False
    )
    op.create_index(
        op.f("ix_price_items_vendor_code"), "price_items", ["vendor_code"], unique=False
    )
    op.create_index(
        op.f("ix_price_items_vendor_id"), "price_items", ["vendor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_items_vendor_id"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_vendor_code"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_source_name"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_sku"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_region"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_org_id"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_item_code"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_is_current"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_import_run_id"), table_name="price_items")
    op.drop_index(op.f("ix_price_items_classification_code"), table_name="price_items")
    op.drop_index("idx_price_temporal", table_name="price_items")
    op.drop_index("idx_price_source", table_name="price_items")
    op.drop_index("idx_price_current", table_name="price_items")
    op.drop_index("idx_price_class", table_name="price_items")
    op.drop_index(
        "idx_price_active_unique",
        table_name="price_items",
        postgresql_where=sa.text("is_current = true"),
        sqlite_where=sa.text("is_current = 1"),
    )
    op.drop_table("price_items")
    op.drop_index(op.f("ix_match_flags_price_item_id"), table_name="match_flags")
    op.drop_index(op.f("ix_match_flags_match_result_id"), table_name="match_flags")
    op.drop_index(op.f("ix_match_flags_item_id"), table_name="match_flags")
    op.drop_index("idx_flags_severity", table_name="match_flags")
    op.drop_index("idx_flags_price", table_name="match_flags")
    op.drop_index("idx_flags_match_result", table_name="match_flags")
    op.drop_index("idx_flags_item", table_name="match_flags")
    op.drop_table("match_flags")
    op.drop_index(op.f("ix_price_import_runs_org_id"), table_name="price_import_runs")
    op.drop_table("price_import_runs")
    op.drop_index(op.f("ix_match_results_price_item_id"), table_name="match_results")
    op.drop_index(op.f("ix_match_results_item_id"), table_name="match_results")
    op.drop_index(op.f("ix_match_results_decision"), table_name="match_results")
    op.drop_table("match_results")
    op.drop_index(op.f("ix_items_project_id"), table_name="items")
    op.drop_index(op.f("ix_items_org_id"), table_name="items")
    op.drop_index(op.f("ix_items_classification_code"), table_name="items")
    op.drop_index(op.f("ix_items_canonical_key"), table_name="items")
    op.drop_index("idx_items_class", table_name="items")
    op.drop_index("idx_items_canonical", table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_item_revisions_project_id"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_org_id"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_item_id"), table_name="item_revisions")
    op.drop_index(
        op.f("ix_item_revisions_ingest_timestamp"), table_name="item_revisions"
    )
    op.drop_index(op.f("ix_item_revisions_field_name"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_change_type"), table_name="item_revisions")
    op.drop_index("idx_revisions_org_project_timestamp", table_name="item_revisions")
    op.drop_index("idx_revisions_item_field", table_name="item_revisions")
    op.drop_table("item_revisions")
    op.drop_index("idx_mapping_temporal", table_name="item_mapping")
    op.drop_index(
        "idx_mapping_active",
        table_name="item_mapping",
        postgresql_where=sa.text("end_ts IS NULL"),
        sqlite_where=sa.text("end_ts IS NULL"),
    )
    op.drop_table("item_mapping")
    op.drop_index(op.f("ix_ingest_logs_status"), table_name="ingest_logs")
    op.drop_index(op.f("ix_ingest_logs_started_at"), table_name="ingest_logs")
    op.drop_index(op.f("ix_ingest_logs_project_id"), table_name="ingest_logs")
    op.drop_index(op.f("ix_ingest_logs_org_id"), table_name="ingest_logs")
    op.drop_index("idx_ingest_org_project_started", table_name="ingest_logs")
    op.drop_table("ingest_logs")
    op.drop_index(op.f("ix_documents_doc_type"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_data_sync_log_status"), table_name="data_sync_log")
    op.drop_index(op.f("ix_data_sync_log_source_name"), table_name="data_sync_log")
    op.drop_index(op.f("ix_data_sync_log_run_timestamp"), table_name="data_sync_log")
    op.drop_index("idx_sync_source_health", table_name="data_sync_log")
    op.drop_index("idx_sync_run", table_name="data_sync_log")
    op.drop_index("idx_sync_failures", table_name="data_sync_log")
    op.drop_table("data_sync_log")
    op.drop_index(
        op.f("ix_classification_mappings_org_id"), table_name="classification_mappings"
    )
    op.drop_table("classification_mappings")
    # ### end Alembic commands ###
