"""add_region_to_projects

Revision ID: 1553cad23ea9
Revises: bdee69de9573
Create Date: 2025-11-30 09:18:34.077846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1553cad23ea9'
down_revision: Union[str, None] = 'bdee69de9573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('region', sa.Text(), nullable=False, server_default='EU'))
    
    # New indexes for training examples (safe to keep)
    op.create_index(op.f('ix_training_examples_org_id'), 'training_examples', ['org_id'], unique=False)
    op.create_index(op.f('ix_training_examples_price_item_id'), 'training_examples', ['price_item_id'], unique=False)
    op.create_index(op.f('ix_training_examples_source_item_id'), 'training_examples', ['source_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_examples_source_item_id'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_price_item_id'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_org_id'), table_name='training_examples')
    op.alter_column('risk_scores', 'item_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('risk_scores', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('projects', 'region')
    op.alter_column('project_documents', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('extracted_items', 'converted_item_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('extracted_items', 'document_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('extracted_items', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index('idx_documents_embedding', table_name='documents', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('documents', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sa.NUMERIC(precision=1536),
               existing_nullable=False)
    op.alter_column('compliance_rules', 'source_document_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('compliance_rules', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_compliance_results_rule_id'), table_name='compliance_results')
    op.drop_index('idx_compliance_results_rule', table_name='compliance_results')
    op.drop_index('idx_compliance_results_item', table_name='compliance_results')
    op.alter_column('compliance_results', 'rule_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('compliance_results', 'item_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('compliance_results', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
