"""add_project_classification_mappings

Revision ID: 1ea2a49487db
Revises: 3314906526e2
Create Date: 2025-11-23 17:15:50.984414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ea2a49487db"
down_revision: Union[str, None] = "3314906526e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_classification_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("local_code", sa.String(length=50), nullable=False),
        sa.Column("standard_code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_id", "project_id", "local_code", name="uq_project_local_code"
        ),
    )
    op.create_index(
        "idx_project_classification_lookup",
        "project_classification_mappings",
        ["org_id", "project_id", "local_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_classification_mappings_org_id"),
        "project_classification_mappings",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_classification_mappings_project_id"),
        "project_classification_mappings",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_classification_mappings_project_id"),
        table_name="project_classification_mappings",
    )
    op.drop_index(
        op.f("ix_project_classification_mappings_org_id"),
        table_name="project_classification_mappings",
    )
    op.drop_index(
        "idx_project_classification_lookup",
        table_name="project_classification_mappings",
    )
    op.drop_table("project_classification_mappings")
    # ### end Alembic commands ###
