"""add_link_metadata_to_document_links

Revision ID: 3314906526e2
Revises: 7513aad5ad62
Create Date: 2025-11-23 16:55:08.072216

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3314906526e2"
down_revision: Union[str, None] = "7513aad5ad62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
