"""add_training_examples_table

Revision ID: 4b3b287a6d78
Revises: dea0d4e01d92
Create Date: 2025-11-29 19:59:33.830840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b3b287a6d78"
down_revision: Union[str, None] = "dea0d4e01d92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_examples",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("item_family", sa.Text(), nullable=False),
        sa.Column("item_type", sa.Text(), nullable=False),
        sa.Column("item_description", sa.Text(), nullable=True),
        sa.Column("target_classification_code", sa.Text(), nullable=False),
        sa.Column("source_item_id", sa.Uuid(), nullable=False),
        sa.Column("price_item_id", sa.Uuid(), nullable=False),
        sa.Column("feedback_type", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index(op.f('ix_training_examples_org_id'), 'training_examples', ['org_id'], unique=False)
    # op.create_index(op.f('ix_training_examples_price_item_id'), 'training_examples', ['price_item_id'], unique=False)
    # op.create_index(op.f('ix_training_examples_source_item_id'), 'training_examples', ['source_item_id'], unique=False)
    # op.create_index(op.f('ix_training_examples_target_classification_code'), 'training_examples', ['target_classification_code'], unique=False)
    op.create_index(
        op.f("ix_training_examples_target_classification_code"),
        "training_examples",
        ["target_classification_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_training_examples_target_classification_code"),
        table_name="training_examples",
    )
    op.drop_index(
        op.f("ix_training_examples_source_item_id"), table_name="training_examples"
    )
    op.drop_index(
        op.f("ix_training_examples_price_item_id"), table_name="training_examples"
    )
    op.drop_index(op.f("ix_training_examples_org_id"), table_name="training_examples")
    op.drop_table("training_examples")
    # ### end Alembic commands ###
