"""add_price_sources_table

Revision ID: 910b9e6e339a
Revises: 1553cad23ea9
Create Date: 2025-12-04 12:11:55.578780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "910b9e6e339a"
down_revision: Union[str, None] = "1553cad23ea9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cache_ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("rate_limit_seconds", sa.Float(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_status", sa.Text(), nullable=True),
        sa.Column("last_sync_items_count", sa.Integer(), nullable=True),
        sa.Column("last_sync_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "domain", name="uq_price_source_domain"),
    )
    op.create_index(
        "idx_price_sources_enabled",
        "price_sources",
        ["org_id", "enabled"],
        unique=False,
    )
    op.create_index(
        "idx_price_sources_last_sync",
        "price_sources",
        ["org_id", "last_sync_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_sources_domain"), "price_sources", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_price_sources_enabled"), "price_sources", ["enabled"], unique=False
    )
    op.create_index(
        op.f("ix_price_sources_org_id"), "price_sources", ["org_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_sources_org_id"), table_name="price_sources")
    op.drop_index(op.f("ix_price_sources_enabled"), table_name="price_sources")
    op.drop_index(op.f("ix_price_sources_domain"), table_name="price_sources")
    op.drop_index("idx_price_sources_last_sync", table_name="price_sources")
    op.drop_index("idx_price_sources_enabled", table_name="price_sources")
    op.drop_table("price_sources")
    # ### end Alembic commands ###
