"""add_qa_checklists_table

Revision ID: a9670b6b1cef
Revises: 1ea2a49487db
Create Date: 2025-11-23 23:38:59.762711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9670b6b1cef'
down_revision: Union[str, None] = '1ea2a49487db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_checklists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('checklist_items', sa.JSON(), nullable=False),
    sa.Column('source_documents', sa.JSON(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completion_percent', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completion_percent >= 0 AND completion_percent <= 100', name='check_completion_range'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qa_checklists_org_project', 'qa_checklists', ['org_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_qa_checklists_item_id'), 'qa_checklists', ['item_id'], unique=True)
    op.create_index(op.f('ix_qa_checklists_org_id'), 'qa_checklists', ['org_id'], unique=False)
    op.create_index(op.f('ix_qa_checklists_project_id'), 'qa_checklists', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_checklists_project_id'), table_name='qa_checklists')
    op.drop_index(op.f('ix_qa_checklists_org_id'), table_name='qa_checklists')
    op.drop_index(op.f('ix_qa_checklists_item_id'), table_name='qa_checklists')
    op.drop_index('idx_qa_checklists_org_project', table_name='qa_checklists')
    op.drop_table('qa_checklists')
    # ### end Alembic commands ###
