"""add_intelligence_models

Revision ID: b3d141521dae
Revises: 5ad4c7482ca2
Create Date: 2025-11-27 17:14:53.197878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b3d141521dae'
down_revision: Union[str, None] = '5ad4c7482ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_org_id'), 'compliance_rules', ['org_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_results_item_id'), 'compliance_results', ['item_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_org_id'), 'compliance_results', ['org_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_project_id'), 'compliance_results', ['project_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('total_risk_score', sa.Float(), nullable=False),
    sa.Column('confidence_risk', sa.Float(), nullable=False),
    sa.Column('price_risk', sa.Float(), nullable=False),
    sa.Column('data_quality_risk', sa.Float(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('total_risk_score >= 0 AND total_risk_score <= 100', name='check_total_risk_range'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_item_id'), 'risk_scores', ['item_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_org_id'), 'risk_scores', ['org_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_project_id'), 'risk_scores', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_project_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_org_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_item_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_compliance_results_project_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_org_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_item_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_compliance_rules_org_id'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
