"""update_compliance_models

Revision ID: bdee69de9573
Revises: e09b3441d3a4
Create Date: 2025-11-29 21:19:17.253640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bdee69de9573"
down_revision: Union[str, None] = "e09b3441d3a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Update compliance_results
    with op.batch_alter_table("compliance_results", schema=None) as batch_op:
        batch_op.drop_index("ix_compliance_results_project_id")
        batch_op.drop_index("ix_compliance_results_org_id")
        batch_op.add_column(
            sa.Column("status", sa.Text(), nullable=False, server_default="warning")
        )
        batch_op.drop_column("project_id")
        batch_op.drop_column("passed")
        batch_op.drop_column("org_id")
        batch_op.create_index(
            batch_op.f("ix_compliance_results_status"), ["status"], unique=False
        )
        # Re-create indexes if needed, but batch_op handles some automatically

    # Update compliance_rules
    with op.batch_alter_table("compliance_rules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("project_id", sa.Text(), nullable=False, server_default="default")
        )
        batch_op.add_column(
            sa.Column("rule_logic", sa.JSON(), nullable=False, server_default="{}")
        )
        batch_op.add_column(sa.Column("source_document_id", sa.UUID(), nullable=True))
        batch_op.add_column(
            sa.Column("created_by", sa.Text(), nullable=False, server_default="system")
        )
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=True)
        batch_op.drop_column("rule_type")
        batch_op.drop_column("configuration")
        batch_op.drop_column("severity")
        batch_op.drop_column("is_active")
        batch_op.create_index(
            batch_op.f("ix_compliance_rules_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_compliance_rules_source_document_id"),
            ["source_document_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_compliance_rules_documents",
            "documents",
            ["source_document_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert compliance_rules
    with op.batch_alter_table("compliance_rules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_active", sa.BOOLEAN(), nullable=False, server_default="1")
        )
        batch_op.add_column(
            sa.Column("severity", sa.TEXT(), nullable=False, server_default="info")
        )
        batch_op.add_column(
            sa.Column("configuration", sa.JSON(), nullable=False, server_default="{}")
        )
        batch_op.add_column(
            sa.Column("rule_type", sa.TEXT(), nullable=False, server_default="general")
        )
        batch_op.drop_constraint("fk_compliance_rules_documents", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_compliance_rules_source_document_id"))
        batch_op.drop_index(batch_op.f("ix_compliance_rules_project_id"))
        batch_op.alter_column("description", existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column("created_by")
        batch_op.drop_column("source_document_id")
        batch_op.drop_column("rule_logic")
        batch_op.drop_column("project_id")

    # Revert compliance_results
    with op.batch_alter_table("compliance_results", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("org_id", sa.TEXT(), nullable=False, server_default="default")
        )
        batch_op.add_column(
            sa.Column("passed", sa.BOOLEAN(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("project_id", sa.TEXT(), nullable=False, server_default="default")
        )
        batch_op.drop_index(batch_op.f("ix_compliance_results_status"))
        batch_op.drop_column("status")

    # ### end Alembic commands ###
