"""add_checklist_templates_table

Revision ID: c135f9f91e99
Revises: a9670b6b1cef
Create Date: 2025-11-24 15:21:18.927274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c135f9f91e99"
down_revision: Union[str, None] = "a9670b6b1cef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        classification_codes_type = sa.ARRAY(sa.Text())
    else:
        classification_codes_type = sa.JSON()

    op.create_table(
        "checklist_templates",
        sa.Column("id", sa.Uuid(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("classification_codes", classification_codes_type, nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("template_items", sa.JSON(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_checklist_templates_builtin",
        "checklist_templates",
        ["is_builtin"],
        unique=False,
    )
    op.create_index(
        "idx_checklist_templates_codes",
        "checklist_templates",
        ["classification_codes"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_checklist_templates_codes", table_name="checklist_templates")
    op.drop_index("idx_checklist_templates_builtin", table_name="checklist_templates")
    op.drop_table("checklist_templates")
    # ### end Alembic commands ###
