"""change_classification_code_to_string

Revision ID: c49e4d2570ce
Revises: 473516d1f7d6
Create Date: 2025-11-25 12:26:03.376956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49e4d2570ce'
down_revision: Union[str, None] = '473516d1f7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'classification_code',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True,
               postgresql_using='classification_code::text')
    op.alter_column('price_items', 'classification_code',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False,
               postgresql_using='classification_code::text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_items', 'classification_code',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('items', 'classification_code',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
