"""add element_id to items

Revision ID: dea0d4e01d92
Revises: dbd7f4bf0a5d
Create Date: 2025-11-29 18:45:11.336067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dea0d4e01d92"
down_revision: Union[str, None] = "dbd7f4bf0a5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("element_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "element_id")
    # ### end Alembic commands ###
