"""add_hnsw_index_to_documents

Revision ID: e09b3441d3a4
Revises: 4b3b287a6d78
Create Date: 2025-11-29 20:48:08.755741

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e09b3441d3a4"
down_revision: Union[str, None] = "4b3b287a6d78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite does not support HNSW indexes via pgvector.
    # This migration is primarily for the Postgres staging/prod environment.
    # We wrap it in a dialect check or just let it fail gracefully on SQLite if needed,
    # but Alembic usually tries to run it.
    # For SQLite dev, we can skip the HNSW index creation or use a conditional.

    bind = op.get_bind()
    if bind.engine.name == "postgresql":
        op.create_index(
            "idx_documents_embedding",
            "documents",
            ["embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )

    # Ensure training example indexes exist (idempotent)
    # op.create_index(op.f('ix_training_examples_org_id'), 'training_examples', ['org_id'], unique=False)
    # op.create_index(op.f('ix_training_examples_price_item_id'), 'training_examples', ['price_item_id'], unique=False)
    # op.create_index(op.f('ix_training_examples_source_item_id'), 'training_examples', ['source_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == "postgresql":
        op.drop_index(
            "idx_documents_embedding",
            table_name="documents",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )

    # op.drop_index(op.f('ix_training_examples_source_item_id'), table_name='training_examples')
    # op.drop_index(op.f('ix_training_examples_price_item_id'), table_name='training_examples')
    # op.drop_index(op.f('ix_training_examples_org_id'), table_name='training_examples')
    # ### end Alembic commands ###
