"""Add attributes to items

Revision ID: ea73c2a4cb4c
Revises: 03e6ef7bacfe
Create Date: 2025-11-23 15:34:50.685319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea73c2a4cb4c'
down_revision: Union[str, None] = '03e6ef7bacfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('attributes', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'attributes')
    # ### end Alembic commands ###
