"""add_bulk_import_tables

Revision ID: edc5a6fe8856
Revises: 910b9e6e339a
Create Date: 2025-12-04 14:14:15.682094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "edc5a6fe8856"
down_revision: Union[str, None] = "910b9e6e339a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_imports_org_id"), "price_imports", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_price_imports_project_id"),
        "price_imports",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_imports_status"), "price_imports", ["status"], unique=False
    )

    op.create_table(
        "price_import_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Text(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("vendor_code", sa.Text(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["import_id"], ["price_imports.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_import_items_import_id"),
        "price_import_items",
        ["import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_import_items_org_id"),
        "price_import_items",
        ["org_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_price_imports_status"), table_name="price_imports")
    op.drop_index(op.f("ix_price_imports_project_id"), table_name="price_imports")
    op.drop_index(op.f("ix_price_imports_org_id"), table_name="price_imports")
    op.drop_table("price_imports")
    # ### end Alembic commands ###
